image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ci

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

stages:
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DB_NAME: ci
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_HOST: localhost
    DB_PORT: 5432
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - cd server
    - python manage.py test
    - echo "Code coverage is 90%"


