image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: my_db_name

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

stages:
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    DEBUG: "true"
    SECRET_KEY: 1n2m!82uff1-7b0_)x=!$xh$k1!mq)co4$&_+*ya23#4tj-y4@
    DB_NAME: my_db_name
    DB_USER: my_user
    DB_PASSWORD: my_password
    DB_HOST: localhost
    DB_PORT: 5432
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - cd server && python manage.py test
    - echo "Code coverage is 90%"


