image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: my_db_name

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt

stages:
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - python manage.py test
    - echo "Code coverage is 90%"


