# Generated by Django 3.2.4 on 2021-08-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employe_org', to='accounts.organization', verbose_name='Внешний ключ на организацию'),
            preserve_default=False,
        ),
    ]
