# Generated by Django 3.2.4 on 2021-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tg_username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Юзернейм телеграм юзера'),
        ),
    ]
