# Generated by Django 3.2.4 on 2021-06-10 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210607_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
