# Generated by Django 3.2.4 on 2021-08-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_company',
        ),
    ]
