# Generated by Django 3.2.4 on 2021-08-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_review', models.TextField(max_length=500, verbose_name='текст отзыва')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_name', to='accounts.employee', verbose_name='имя пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'Reviews',
            },
        ),
    ]
