# Generated by Django 3.2.4 on 2021-08-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_review_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancechange',
            name='notification_text',
        ),
    ]
