# Generated by Django 3.2.4 on 2021-06-12 07:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen5bot', '0002_auto_20210605_0809'),
        ('accounts', '0006_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('tg_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kitchen5bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Users',
            },
        ),
    ]
