# Generated by Django 3.2.4 on 2021-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='Bishkek', max_length=400),
        ),
        migrations.AddField(
            model_name='organization',
            name='bonus_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='leave_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment',
            field=models.CharField(choices=[('actual', 'фактический расчет'), ('cumulative', 'накопительный расчет')], default=('actual', 'фактический расчет'), max_length=400),
        ),
    ]
