# Generated by Django 3.2.4 on 2021-06-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210614_1002'),
        ('accounts', '0011_usertoken'),
    ]

    operations = [
    ]
