# Generated by Django 3.2.4 on 2021-06-18 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen5bot', '0002_auto_20210605_0809'),
        ('accounts', '0013_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(default='Bishkek', max_length=400, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bonus_activation',
            field=models.BooleanField(default=False, verbose_name='Возможность активирования бонуса'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли компания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leave_review',
            field=models.BooleanField(default=True, verbose_name='Возможность оставлять отзывы'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment',
            field=models.CharField(choices=[('actual', 'фактический расчет'), ('cumulative', 'накопительный расчет')], default=('actual', 'фактический расчет'), max_length=400, verbose_name='Тип расчета'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Вторичный ключ(UUID)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли пользователь'),
        ),
        migrations.AlterField(
            model_name='users',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Внешний ключ на организацию'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tg_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kitchen5bot.telegramuser', verbose_name='Пользователь телеграма'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Username'),
        ),
    ]
