# Generated by Django 3.2.4 on 2021-06-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210618_1208'),
        ('accounts', '0014_auto_20210619_1351'),
    ]

    operations = [
    ]
