# Generated by Django 3.2.4 on 2021-06-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_0014_auto_20210618_1208_0014_auto_20210619_1351'),
        ('accounts', '0015_usertoken_created_at'),
    ]

    operations = [
    ]
