# Generated by Django 3.2.4 on 2021-06-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20210622_1025'),
        ('accounts', '0016_merge_20210622_1040'),
    ]

    operations = [
    ]
