# Generated by Django 3.2.4 on 2021-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20210622_1031'),
        ('accounts', '0017_merge_20210623_0859'),
    ]

    operations = [
    ]
