# Generated by Django 3.2.4 on 2021-06-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20210624_0903'),
        ('accounts', '0018_merge_20210624_0930'),
    ]

    operations = [
    ]
