# Generated by Django 3.2.4 on 2021-06-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20210624_0724'),
        ('accounts', '0019_merge_20210624_0940'),
    ]

    operations = [
    ]
