# Generated by Django 3.2.4 on 2021-06-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20210625_1833'),
        ('accounts', '0020_users_is_admin'),
    ]

    operations = [
    ]
