# Generated by Django 3.2.4 on 2021-06-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20210625_0939'),
        ('accounts', '0021_merge_0020_merge_20210625_1833_0020_users_is_admin'),
    ]

    operations = [
    ]
