# Generated by Django 3.2.4 on 2021-07-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_20210629_1137'),
        ('accounts', '0022_merge_20210630_0907'),
    ]

    operations = [
    ]
