# Generated by Django 3.2.4 on 2021-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20210701_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
