# Generated by Django 3.2.4 on 2021-07-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen5bot', '0002_auto_20210605_0809'),
        ('accounts', '0024_usertoken_activated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employe',
        ),
    ]
