# Generated by Django 3.2.4 on 2021-07-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_20210630_0948'),
        ('accounts', '0025_rename_users_employe'),
    ]

    operations = [
    ]
