# Generated by Django 3.2.4 on 2021-07-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_users_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_org', to='accounts.organization', verbose_name='Внешний ключ на организацию'),
        ),
    ]
