# Generated by Django 3.2.4 on 2021-07-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_20210702_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='activated',
        ),
    ]
