# Generated by Django 3.2.4 on 2021-07-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210707_1815'),
        ('accounts', '0028_auto_20210706_1205'),
    ]

    operations = [
    ]
