# Generated by Django 3.2.4 on 2021-07-07 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210707_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
