# Generated by Django 3.2.4 on 2021-07-07 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_balancechange_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='sum_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
    ]
