# Generated by Django 3.2.4 on 2021-07-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_balancechange_sum_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bal_em', to='accounts.employe', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='type',
            field=models.CharField(choices=[('accrual', 'Начисление'), ('write-off', 'Списание')], max_length=200, verbose_name='Тип'),
        ),
    ]
