# Generated by Django 3.2.4 on 2021-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210709_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='total_balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общий баланс'),
        ),
    ]
