# Generated by Django 3.2.4 on 2021-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_balancechange_sum_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='balance_after_transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
