# Generated by Django 3.2.4 on 2021-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_balancechange_balance_after_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='notification_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
