# Generated by Django 3.2.4 on 2021-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_balancechange_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='tg_firstname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя телеграм юзера'),
        ),
        migrations.AddField(
            model_name='employe',
            name='tg_id',
            field=models.CharField(default=1234567, max_length=128, verbose_name='ID телеграм юзера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='tg_lastname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия телеграм юзера'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='tg_user',
            field=models.CharField(max_length=128, verbose_name='Юзернейм телеграм юзера'),
        ),
    ]
