# Generated by Django 3.2.4 on 2021-07-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210728_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='tg_user',
            new_name='tg_username',
        ),
    ]
