# Generated by Django 3.2.4 on 2021-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0014_auto_20210720_0950'),
        ('accounts', '0039_rename_tg_user_employe_tg_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='balancechange',
            old_name='employe',
            new_name='employee',
        ),
    ]
