# Generated by Django 3.2.4 on 2021-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Надбавка')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за надбавку')),
            ],
        ),
    ]
