# Generated by Django 3.2.4 on 2021-08-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('KitchenWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='accounts.organization', verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'commands',
            },
        ),
    ]
