# Generated by Django 3.2.4 on 2021-08-06 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='discount',
            field=models.IntegerField(default=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='offering',
            name='special_offering',
            field=models.BooleanField(default=False),
        ),
    ]
