# Generated by Django 3.2.4 on 2021-08-22 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0002_auto_20210819_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.TextField(max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередность Категории'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='qty_portion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Количество доступных порций на дату'),
        ),
    ]
