# Generated by Django 3.2.4 on 2021-08-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0002_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='title',
        ),
    ]
