# Generated by Django 3.2.4 on 2021-06-18 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0002_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
