# Generated by Django 3.2.4 on 2021-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review'),
        ('KitchenWeb', '0003_remove_command_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='organization',
        ),
        migrations.AddField(
            model_name='command',
            name='organization',
            field=models.ManyToManyField(related_name='commands', to='accounts.Organization', verbose_name='Организации'),
        ),
    ]
