# Generated by Django 3.2.4 on 2021-08-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0003_auto_20210822_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='special_offering',
        ),
    ]
