# Generated by Django 3.2.4 on 2021-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0003_alter_category_options'),
        ('KitchenWeb', '0003_auto_20210618_0700'),
    ]

    operations = [
    ]
