# Generated by Django 3.2.4 on 2021-08-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0004_auto_20210804_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
