# Generated by Django 3.2.4 on 2021-08-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0002_auto_20210806_0948'),
        ('KitchenWeb', '0004_auto_20210804_1344'),
    ]

    operations = [
    ]
