# Generated by Django 3.2.4 on 2021-08-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0005_alter_cart_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
