# Generated by Django 3.2.4 on 2021-08-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0005_merge_0002_auto_20210806_0948_0004_auto_20210804_1344'),
        ('KitchenWeb', '0007_cart'),
    ]

    operations = [
    ]
