# Generated by Django 3.2.4 on 2021-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0007_garnish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Дополнение к позиции')),
                ('sampling_order', models.IntegerField(verbose_name='Очередность при выборке')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена')),
                ('extra_price', models.JSONField(blank=True, null=True, verbose_name='Дополнительная цена')),
            ],
            options={
                'verbose_name': 'Дополнение к позиции',
                'verbose_name_plural': 'Дополнения к позициям',
                'db_table': 'Additional',
            },
        ),
    ]
