# Generated by Django 3.2.4 on 2021-07-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0008_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('additional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_additional', to='KitchenWeb.additional', verbose_name='Дополнения')),
                ('garnish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_garnish', to='KitchenWeb.garnish', verbose_name='Гарнир')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offering_position', to='KitchenWeb.dish', verbose_name='Позиция')),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_supplement', to='KitchenWeb.supplement', verbose_name='Надбавка')),
            ],
            options={
                'verbose_name': 'Предложение по позиции',
                'verbose_name_plural': 'Предложения по позициям',
                'db_table': 'offerings',
            },
        ),
    ]
