# Generated by Django 3.2.4 on 2021-08-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0008_merge_20210812_0810'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='basket',
        ),
    ]
