# Generated by Django 3.2.4 on 2021-07-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0009_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='qty_portion',
            field=models.IntegerField(default=0),
        ),
    ]
