# Generated by Django 3.2.4 on 2021-07-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0010_offering_qty_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_position', to='KitchenWeb.dish', verbose_name='Позиция'),
        ),
    ]
