# Generated by Django 3.2.4 on 2021-07-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_balancechange_notification_text'),
        ('KitchenWeb', '0010_offering_qty_portion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_offering', to='KitchenWeb.offering', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_user', to='accounts.employe', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'basket',
            },
        ),
    ]
