# Generated by Django 3.2.4 on 2021-07-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0011_alter_offering_position'),
        ('KitchenWeb', '0012_order'),
    ]

    operations = [
    ]
