# Generated by Django 3.2.4 on 2021-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenWeb', '0013_merge_0011_alter_offering_position_0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='additional',
        ),
        migrations.AddField(
            model_name='offering',
            name='additional',
            field=models.ManyToManyField(blank=True, null=True, related_name='offering_additional', to='KitchenWeb.Additional', verbose_name='Дополнения'),
        ),
        migrations.RemoveField(
            model_name='offering',
            name='garnish',
        ),
        migrations.AddField(
            model_name='offering',
            name='garnish',
            field=models.ManyToManyField(blank=True, null=True, related_name='offering_garnish', to='KitchenWeb.Garnish', verbose_name='Гарнир'),
        ),
        migrations.RemoveField(
            model_name='offering',
            name='supplement',
        ),
        migrations.AddField(
            model_name='offering',
            name='supplement',
            field=models.ManyToManyField(blank=True, null=True, related_name='offering_supplement', to='KitchenWeb.Supplement', verbose_name='Надбавка'),
        ),
    ]
